config/routes.rb
Rails.application.routes.draw do
  get 'pages/play'
  devise_for :users
  resources :comments
  resources :cards
  resources :formats
  resources :editions

  root to: "pages#play"
end

app/models/format.rb
# == Schema Information
#
# Table name: formats
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Format < ApplicationRecord
    has_many :edition_formats
    has_many :comments
    has_many :editions, through: :edition_formats
    has_many :cards, through: :comments

    validates :name, uniqueness: true
end

app/controllers/formats_controller.rb
class FormatsController < ApplicationController
  before_action :set_format, only: %i[ show edit update destroy ]

  # GET /formats or /formats.json
  def index
    @formats = Format.all
  end

  # GET /formats/1 or /formats/1.json
  def show
  end

  # GET /formats/new
  def new
    @format = Format.new
  end

  # GET /formats/1/edit
  def edit
  end

  # POST /formats or /formats.json
  def create
    @format = Format.new(format_params)

    respond_to do |format|
      if @format.save
        format.html { redirect_to format_url(@format), notice: "Format was successfully created." }
        format.json { render :show, status: :created, location: @format }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @format.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /formats/1 or /formats/1.json
  def update
    respond_to do |format|
      if @format.update(format_params)
        format.html { redirect_to format_url(@format), notice: "Format was successfully updated." }
        format.json { render :show, status: :ok, location: @format }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @format.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /formats/1 or /formats/1.json
  def destroy
    @format.destroy

    respond_to do |format|
      format.html { redirect_to formats_url, notice: "Format was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_format
      @format = Format.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def format_params
      params.require(:format).permit(:name)
    end
end

app/helpers/formats_helper.rb
module FormatsHelper
end

app/views/formats/_form.html.erb
<%= form_with(model: format, class: "contents") do |form| %>
  <% if format.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(format.errors.count, "error") %> prohibited this format from being saved:</h2>

      <ul>
        <% format.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/formats/_format.html.erb
<div id="<%= dom_id format %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= format.name %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this format", format, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this format', edit_format_path(format), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/formats/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing format</h1>

  <%= render "form", format: @format %>

  <%= link_to "Show this format", @format, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to formats", formats_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/formats/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Formats</h1>
    <%= link_to 'New format', new_format_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="formats" class="min-w-full">
    <%= render @formats %>
  </div>
</div>

app/views/formats/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New format</h1>

  <%= render "form", format: @format %>

  <%= link_to 'Back to formats', formats_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/formats/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @format %>

    <%= link_to 'Edit this format', edit_format_path(@format), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this format', format_path(@format), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to formats', formats_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>