config/routes.rb
Rails.application.routes.draw do
  get 'pages/play'
  devise_for :users
  resources :comments
  resources :cards
  resources :formats
  resources :editions

  root to: "pages#play"
end

app/models/card.rb
# == Schema Information
#
# Table name: cards
#
#  id           :bigint           not null, primary key
#  name         :string
#  img          :binary
#  minimal_cost :integer
#  white        :boolean
#  red          :boolean
#  black        :boolean
#  green        :boolean
#  blue         :boolean
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Card < ApplicationRecord
    has_many :card_editions
    has_many :editions, through: :card_editions
    has_many :comments
    accepts_nested_attributes_for :comments, reject_if: :all_blank, allow_destroy: true
    has_many :formats, through: :comments
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: %i[ show edit update destroy ]

  # GET /cards or /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1 or /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards or /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to card_url(@card), notice: "Card was successfully created." }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1 or /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to card_url(@card), notice: "Card was successfully updated." }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1 or /cards/1.json
  def destroy
    @card.destroy

    respond_to do |format|
      format.html { redirect_to cards_url, notice: "Card was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def card_params
      params.require(:card).permit(:name, :img, :minimal_cost, :white, :red, :black, :green, :blue, comments_attributes: [ :id, :_destroy, :text, :format_id ])
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_card.html.erb
<div id="<%= dom_id card %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= card.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Img:</strong>
    <%= card.img %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Minimal cost:</strong>
    <%= card.minimal_cost %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">White:</strong>
    <%= card.white %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Red:</strong>
    <%= card.red %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Black:</strong>
    <%= card.black %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Green:</strong>
    <%= card.green %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Blue:</strong>
    <%= card.blue %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this card", card, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this card', edit_card_path(card), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/cards/_comment_form.html.erb
<div class="nested-form-wrapper inline-block ml-2 py-3 px-5" data-new-record="<%= form.object.new_record? %>">
  <%= form.label :text %>
  <%= form.text_field :text %>
  <%= form.collection_select :format_id, Format.order(:name), :id, :name %>

  <button type="button" data-action="nested-form#remove" class="ml-2 rounded-lg py-3 px-5 bg-red-500 text-white font-medium">Delete</button>

  <%= form.hidden_field :_destroy %>
</div>

app/views/cards/_form.html.erb
<%= form_with(model: card, class: "contents", data: { controller: 'nested-form', nested_form_wrapper_selector_value: '.nested-form-wrapper' }) do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
        <% card.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :img %>
    <%= form.text_field :img, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :minimal_cost %>
    <%= form.number_field :minimal_cost, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :white %>
    <%= form.check_box :white, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="my-5">
    <%= form.label :red %>
    <%= form.check_box :red, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="my-5">
    <%= form.label :black %>
    <%= form.check_box :black, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="my-5">
    <%= form.label :green %>
    <%= form.check_box :green, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="my-5">
    <%= form.label :blue %>
    <%= form.check_box :blue, class: "block mt-2 h-5 w-5" %>
  </div>

  <template data-nested-form-target="template">
    <%= form.fields_for :comments, Comment.new, child_index: 'NEW_RECORD' do |comment_fields| %>
      <%= render "comment_form", form: comment_fields %>
    <% end %>
  </template>

  <button type="button" data-action="nested-form#add" class="block rounded-lg py-3 px-5 my-2 bg-blue-500 text-white font-medium">Add format</button>

  <%= form.fields_for :comments do |comment_fields| %>
    <%= render "comment_form", form: comment_fields %>
  <% end %>

  <!-- Inserted elements will be injected before that target. -->
  <div data-nested-form-target="target"></div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing card</h1>

  <%= render "form", card: @card %>

  <%= link_to "Show this card", @card, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to cards", cards_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/cards/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Cards</h1>
    <%= link_to 'New card', new_card_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="cards" class="min-w-full">
    <%= render @cards %>
  </div>
</div>

app/views/cards/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New card</h1>

  <%= render "form", card: @card %>
  
  <%= link_to 'Back to cards', cards_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/cards/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">

  <div class="mx-auto">

    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @card %>

    <%= link_to 'Edit this card', edit_card_path(@card), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this card', card_path(@card), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>

    <%= link_to 'Back to cards', cards_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  
  </div>
</div>